# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=11, max_length=11),
            preserve_default=False,
        ),
    ]
