# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=11, max_length=6),
            preserve_default=False,
        ),
    ]
