# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0004_auto_20161202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postuser',
            field=models.IntegerField(max_length=8),
        ),
    ]
