# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0006_auto_20161202_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='datelastvoice',
            field=models.CharField(blank=True, default='nothing', max_length=120),
        ),
        migrations.AlterField(
            model_name='posts',
            name='postuser',
            field=models.IntegerField(blank=True, default=1, max_length=8),
        ),
    ]
