# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0007_auto_20161202_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-commentsquantity']},
        ),
    ]
