# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0008_auto_20161202_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['-likedquantity']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commenttopost',
            new_name='posts',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='commentuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='likedphoto',
            new_name='photos',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='likeduser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='likeds',
            new_name='likedquantity',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='phototype',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='photouser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='postuser',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profileuser',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='datelastcomment',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='datelike',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='dateupload',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photofile',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='datelastvoice',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='userprofile',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='basis.Userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photos',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default=11, upload_to='photo/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photostype',
            name='type',
            field=models.CharField(default='Others', max_length=23),
        ),
        migrations.AlterField(
            model_name='posts',
            name='commentsquantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head',
            field=models.ImageField(blank=True, null=True, upload_to='head'),
        ),
    ]
