# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0010_auto_20161205_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='belikedquantity',
            field=models.IntegerField(default=0),
        ),
    ]
