# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0011_userprofile_belikedquantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-belikedquantity']},
        ),
    ]
