# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basis', '0012_auto_20161205_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photosay',
            field=models.CharField(max_length=128),
        ),
    ]
